# How to Deploy PostgreSQL on Kubernetes
# https://phoenixnap.com/kb/postgresql-kubernetes
# Step 2: Create and Apply Persistent Storage Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"