# How to Deploy PostgreSQL on Kubernetes
# https://phoenixnap.com/kb/postgresql-kubernetes
# Step 3: Create and Apply Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi