# /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/DM-SP04-C04-JENKINS-CPA-MAY2024/dm-ds-cdo-may24-jenkins/dr01-python-microservices6/k8s-test4/fastapi-cast.yaml
# sudo kubectl -n dev create configmap nginx-config --from-file=nginx_config.conf
# sudo kubectl -n dev get configmap
# sudo kubectl -n dev edit configmap nginx-config
# sudo kubectl -n dev describe configmap nginx-conf
# sudo kubectl -n dev get configmap nginx-config -o json
# sudo kubectl -n dev get configmap nginx-config -o "jsonpath={.data['nginx_config\.conf']# Notons que le '.' dans max_allowed_packet.cnf doit être échappé
# sudo kubectl -n dev get configmap nginx-config -o json > nginx_config.json

apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dm-ds-jenkins
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2025-05-09T17:21:33Z
  name: nginx-config
  namespace: dev
  resourceVersion: "103950"
  uid: db8fbd55-4346-4536-abf5-8c2724750c5b
data:
  nginx_config.conf: |
    server {
      listen 8085;
      location /api/v1/casts {

        proxy_pass http://cast_service:8005/api/v1/casts;

        }
      }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-config-pv
  labels:
    app: fastapi-casts
  namespace: dev
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/DM-SP04-C04-JENKINS-CPA-MAY2024/dm-ds-cdo-may24-jenkins/datas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-cast
  creationTimestamp: null
  labels:
    app: cast-db
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config-pvc
  creationTimestamp: null
  labels:
    app: nginx-config
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-service-claim0
  creationTimestamp: null
  labels:
    app: fastapi-casts
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
  labels:
    app: fastapi-casts
  namespace: dev
data: # echo -n "postgres:..." | base64
  postgres_db: Y2FzdF9kYl9jcGE=
  postgres_password: Y2FzdF9kYl9jcGFfcGFzc3dvcmQ=
  postgres_user: Y2FzdF9kYl9jcGFfdXNlcm5hbWU=
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-casts
  template:
    metadata:
      labels:
        app: fastapi-casts
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: cast-db-secret
              key: postgres_db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cast-db-secret
              key: postgres_password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: cast-db-secret
              key: postgres_user
        image: postgres:12.1-alpine
        livenessProbe:
          exec:
            command:
            - 'pg_isready -U  -d '
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 10
        name: cast-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: postgres-data-cast
      restartPolicy: Always
      volumes:
      - name: postgres-data-cast
        persistentVolumeClaim:
          claimName: postgres-data-cast
---
# /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/DM-SP04-C04-JENKINS-CPA-MAY2024/dm-ds-cdo-may24-jenkins/dr01-python-microservices6/k8s-test4/cast-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service-deployment
  labels:
    app: fastapi-casts
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cast-service
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: cpa8876/casts-ds-fastapi:v.74.0
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: cast-db-secret
                key: postgres_db
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cast-db-secret
                key: postgres_password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: cast-db-secret
                key: postgres_user
          - name: IP_CAST_DB
            value: "10.42.1.40"
          - name: PORT_CAST_DB
            value: "5432"
          - name: DATABASE_URI
            value:  "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(IP_CAST_DB):$(PORT_CAST_DB)/$(POSTGRES_DB)"
        ports:
          - containerPort: 8005
        command: ["uvicorn", "app.main:app", "--root-path", "--reload", "--host", "0.0.0.0", "--port", "8005"]
        resources: {}
        volumeMounts:
          - mountPath: /data/
            name: cast-service-claim0
      volumes:
        - name: cast-service-claim0
          persistentVolumeClaim:
            claimName: cast-service-claim0

---
# /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/DM-SP04-C04-JENKINS-CPA-MAY2024/dm-ds-cdo-may24-jenkins/dr01-python-microservices6/k8s-test4/cast-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cast-service
  labels:
    app: fastapi-casts
  namespace: dev
spec:
#  type: LoadBalancer
  type: NodePort # For INGRESS ClusterIP can be used as well instead of NodePort
  selector:
    app: cast-service
  ports:
  - name: "8005"
    port: 8005
    targetPort: 8005
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - name: "8085"
    port: 8085
    targetPort: 8081
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 8081
          resources: {}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---

