# /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/DM-SP04-C04-JENKINS-CPA-MAY2024/dm-ds-cdo-may24-jenkins/dr01-python-microservices6/cast-service/k8s/cast-deployment.yaml
### BIBLIO
#### DM-JENKIN§S-B623 -  DevOps Project — Part 4 / Dergham Lahcene /Dergham Lahcene; 8 min read; Feb 25, 2023
#####  https://medium.com/@l.dergham/devops-project-part-4-92d6641ed752
apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
type: Opaque
data:
  cast-db-username: ZmFzdGFwaV91c2Vy       # echo $(echo -n "ZmFzdGFwaV91c2Vy" | base64 -d)  :=> fastapi_user
  cast-db-password: ZmFzdGFwaV9wYXNzd2Q=   # echo $(echo -n "ZmFzdGFwaV9wYXNzd2Q=" | base64 -d)  :=> fastapi_passwd
  cast-db-database: ZmFzdGFwaV9kYg==       # echo $(echo -n "ZmFzdGFwaV9kYg==" | base64 -d)  :=> fastapi_db
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db-service
spec:
  selector:
    app: postgres
  ports:
    - name: cast-db-service-port
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
#kind: Deployment
kind: StatefulSet
metadata:
  name: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: cast-db
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cast-db-secret
                  key: cast-db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cast-db-secret
                  key: cast-db-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: cast-db-secret
                  key: cast-db-database
          ports:
            - containerPort: 5432
---
