# # /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/DM-SP04-C04-JENKINS-CPA-MAY2024/dm-ds-cdo-may24-jenkins/dr01-python-microservices6/cast-service/k8s/fastapi-cast-deployment.yaml
##################
### BIBLIO
#### DM-JENKIN§S-B62-3 -  DevOps Project — Part 4 / Dergham Lahcene /Dergham Lahcene; 8 min read; Feb 25, 2023
#####  https://medium.com/@l.dergham/devops-project-part-4-92d6641ed752
---
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  labels:
    app: fastapi
data:
  URL : cG9zdGdyZXNxbDovL2Zhc3RhcGlfdXNlcjpmYXN0YXBpX3Bhc3N3ZEBwb3N0Z3Jlcy1zZXJ2aWNl OjU0MzIvZmFzdGFwaV9kYg== # echo $(echo -n "postgresql://fastapi_user:fastapi_passwd@postgres-service:5432/fastapi_db" | base64) : => cG9zdGdyZXNxbDovL2Zhc3RhcGlfdXNlcjpmYXN0YXBpX3Bhc3N3ZEBwb3N0Z3Jlcy1zZXJ2aWNl OjU0MzIvZmFzdGFwaV9kYg==
---
# fastapi-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-configmap
data:
  database-url: postgres-service
---
# fastapi-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: lahcenedergham/fastapi-image:latest
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: fastapi-secret
                key: URL
          ports:
            - containerPort: 5000
---
