apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config-pvc
  labels:
    app: fastapi-casts
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
