apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-cast
  creationTimestamp: null
  labels:
    app: fastapi-casts
  namespace: dev

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
