apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "charts_cast_db3.fullname" . }}
  labels:
    {{- include "charts_cast_db3.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
    matchLabels:
  selector:
      {{- include "charts_cast_db3.selectorLabels" . | nindent 6 }}
    metadata:
      {{- with .Values.podAnnotations }}
  template:
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "charts_cast_db3.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "charts_cast_db3.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: cast-db
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.cast_db.password | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.cast_db.username | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.cast_db.database | quote }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
             {{- if .Values.persistence.enabled }}
             - name: cast-db-data
               mountPath: {{ .Values.persistence.mountPath }}/data
               subPath: {{ .Values.persistence.subPath }}
               readOnly: false
          {{- end }}
          {{- if or (.Files.Glob "configs/pg_hba.conf") .Values.postgresql.pghba .Values.configMap }}
        - name: postgresql-config-pghba
          mountPath: {{ .Values.persistence.mountPath }}/conf/pg_hba.conf
          subPath: pg_hba.conf
          readOnly: false
        {{- end }}
        {{- if or (.Files.Glob "configs/initdbscripts.sh") .Values.postgresql.initdbscripts .Values.configMap }}
        - name: postgresql-config-initdbscripts
          mountPath: /docker-entrypoint-initdb.d/initdbscripts.sh
          subPath: initdbscripts.sh
          readOnly: false
        {{- end }}
        {{- if or (.Files.Glob "configs/postgresql.conf") .Values.postgresql.config .Values.configMap }}
        - name: postgresql-config
          mountPath: {{ .Values.persistence.mountPath }}/conf/postgresql.conf
          subPath: postgresql.conf
          readOnly: false
        {{- end }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
        {{- if or (.Files.Glob "configs/pg_hba.conf") .Values.postgresql.pghba .Values.postgresql.configMap}}
         - name: cast-db-data
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
