# /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/DM-SP04-C04-JENKINS-CPA-MAY2024/dm-ds-cdo-may24-jenkins/charts/cast-db/environments/dev/values.dev.yaml
# https://search.brave.com/search?q=deploy+postgresql++with+helm+define+database+name+user+and+password&summary=1&conversation=dc22ae482ce1d03139eac3
auth:
  username: fastapi_user      # echo $(echo -n "ZmFzdGFwaV91c2Vy" | base64 -d)  :=> fastapi_user
#  password: fastapi_passwd  # echo $(echo -n "ZmFzdGFwaV9wYXNzd2Q=" | base64 -d)  :=> fastapi_passwd
  database: fastapi_db      # echo $(echo -n "ZmFzdGFwaV9kYg==" | base64 -d)  :=> fastapi_db
#   postgresPassword: postgres_passwd
# https://search.brave.com/search?q=deploy+postgresql++with+helm+define+database+name+user+and+password+secret&summary=1&conversation=110039d2dbb5f96f6df3bc
#auth:
  existingSecret: cast-db-secret
  secretKeys:
#    adminPasswordKey: postgres-password
    userPasswordKey: cast-db-password
#    password: cast-db-password # APP_DB_PASSWORD
  port: 5432
  # initdbArgs 
  # initdbWalDir
  dataDir: /var/lib/postgresql/data/pgdata

# https://search.brave.com/search?q=helm+--+create+namespace+example&summary=1&conversation=49770f42daf4f2e1b3ec9e
  namespace:
  name: baeldung-ops
  environment: dev
  app: cast-db
---
