apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
  namespace: dev
type: Opaque
data:
  cast-db-username: ZmFzdGFwaV91c2Vy       # echo $(echo -n "ZmFzdGFwaV91c2Vy" | base64 -d)  :=> fastapi_user
  cast-db-password: ZmFzdGFwaV9wYXNzd2Q=   # echo $(echo -n "ZmFzdGFwaV9wYXNzd2Q=" | base64 -d)  :=> fastapi_passwd
  cast-db-database: ZmFzdGFwaV9kYg==       # echo $(echo -n "ZmFzdGFwaV9kYg==" | base64 -d)  :=> fastapi_db