apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-deployment
  namespace: dev
spec:
#  type: LoadBalancer
  type: NodePort
  selector:
    app: nginx-service
  ports:
  - name: "8085"
    port: 8085
    targetPort: 8085

