apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  labels:
    app: fastapi
data: # echo -n "postgres:..." | base64
  DB_URL: cG9zdGdyZXMtbW92aWVzLXN0cy0wOmNwYV9tb3ZpZXM6Y3BhX21vdmllc0Bwb3N0Z3Jlcy1tb3ZpZXMtbGIvbW92aWVzX2RiCg==

