apiVersion: v1
kind: Pod
metadata:
  labels:
    type: web 
  name: fastapi-movie
spec:
  containers:
#  - image: nginx
  - image: cpa8876/movie-ds-fastapi:v.73.0
    name: my-fastapi-movie
    env: 
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: fastapi-secret
            key: DB_URL
      - name: CAST_SERVICE_HOST_URL
        valueFrom:
          secretKeyRef:
            name: fastapi-secret
            key: DB_URL
