---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: casts-db-pvc
  namespace: dev
  labels:
    app: casts-db
    namespace: dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
