# /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/python-microservices/docker-compose.yml
version: '3'

services:
  cast_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cast_db_username
      - POSTGRES_PASSWORD=cast_db_password
      - POSTGRES_DB=cast_db_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 10s
    networks:
      - app-network

  cast_service:
    build: ./cast-service
    depends_on:
      - cast_db
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8005
    volumes:
      - ./cast-service/:/app/
    ports:
      - 8005:8005
    environment:
      - DATABASE_URI=postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - 8085:8081
    volumes:
     - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cast_service
# https://stackoverflow.com/questions/50705838/docker-compose-with-nginx-keeps-displaying-welcome-page
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data_movie:
  postgres_data_cast:

