apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: fastapi-casts
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 8081
          resources: {}
          volumeMounts:
            - name: nginx-config-pvc
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config-pvc
          persistentVolumeClaim:
            claimName: nginx-config-pvc
