apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: nginx-service
  ports:
  - name: "8085"
    port: 8085
    targetPort: 8081

