# /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/DM-SP04-C04-JENKINS-CPA-MAY2024/dm-ds-cdo-may24-jenkins/dr01-python-microservices6/k8s-test4/cast-service-deployment.yaml
apiVersion: v1
kind: Pod
metadata:
  name: cast-service-pod
  labels:
    app: fastapi-casts
  namespace: dev
spec:
  containers:
    - name: cast-service
      image: cpa8876/casts-ds-fastapi:v.74.0
      env:
      - name: POSTGRES_DB
        valueFrom:
          secretKeyRef:
            name: cast-db-secret
            key: postgres_db
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: cast-db-secret
            key: postgres_password
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: cast-db-secret
            key: postgres_user
      - name: CAST_DB
        value: 10.42.1.40
      - name: DATABASE_URI
        value: postgresql://cast_db_cpa_username:cast_db_cpa_password@10.42.1.40/cast_db_cpa
      command: ["uvicorn"]
      args: ["app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8005"]
      ports:
        - containerPort: 8005
