# /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/DM-SP04-C04-JENKINS-CPA-MAY2024/dm-ds-cdo-may24-jenkins/dm-jenkins-cpa/cast-service/helm/cast-fastapi/templates/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: cast-fastapi-service
  namespace: {{ .Values.environment | quote }}
spec:
  type: ClusterIP
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  ports:
    - port: {{ .Values.services.cast_fastapi.port }}
  selector:
    app: {{ .Release.Name }}-app
---
