# /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/DM-SP04-C04-JENKINS-CPA-MAY2024/dm-ds-cdo-may24-jenkins/dr01-python-microservices6/k8s/db-movie/postgres-movies-configmap.yaml
# PostgreSQL StatefulSet ConfigMap
# https://www.bmc.com/blogs/kubernetes-postgres/
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-movies-config
  labels:
   app: postgres-movies
data:
  postgres_movies_db: "movies_db"
  postgres_movies_user: "cpa_movies"
  postgres_movies_password: "cpa_movies"
  pgdata_movies: "/data/pgdata"
