# /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/DM-SP04-C04-JENKINS-CPA-MAY2024/dm-ds-cdo-may24-jenkins/dr01-python-microservices6/k8s/db-movie/# PostgreSQL StatefulSet Service
# postgres-service.yaml
# https://www.bmc.com/blogs/kubernetes-postgres/
apiVersion: v1
kind: Service
metadata:
  name: postgres-movies-lb
spec:
  selector:
    app: postgres-movies
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
