# /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/DM-SP04-C04-JENKINS-CPA-MAY2024/dm-ds-cdo-may24-jenkins/dr01-python-microservices6/k8s/db-movie/postgres-movies-sts.yaml
# PostgreSQL StatefulSet
# https://www.bmc.com/blogs/kubernetes-postgres/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-movies-sts
  labels:
    app: fastapi-postgres-dm-jenkins
spec:
  serviceName: postgres-movies-service
  replicas: 2
  selector:
    matchLabels:
      app: postgres-movies-sts
  template:
    metadata:
      labels:
        app: postgres-movies-sts
    spec:
      containers:
      - name: postgres-movies-sts-ctnr
        image: postgres:13.1-alpine
        volumeMounts:
        - name: postgres-movie-disk
          mountPath: /data
      # Config from ConfigMap
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-movies-config
                key: postgres_movies_db
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-movies-config
                key: postgres_movies_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-movies-config
                key: postgres_movies_password
          - name: PGDATA
            valueFrom:
              configMapKeyRef:
                name: postgres-movies-config
                key: pgdata_movies
  # Volume Claim
  volumeClaimTemplates:
  - metadata:
      name: postgres-movie-disk
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 25Gi
