# /home/cpa/Documents/CPA/44_JENKINS/DM.JENKINS/DM-SP04-C04-JENKINS-CPA-MAY2024/dm-ds-cdo-may24-jenkins/dm-jenkins-cpa/cast-service/helm/cast-db/templates/statfulset.yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.environment }}
spec:
  replicas:  {{ .Values.cast_db.replicas }}
  selector:
    matchLabels:
      app: cast-db-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: cast-db-{{ .Release.Name }}
        environment: {{ .Values.environment | quote }}
    spec:
      containers:
        - name: cast-db
          image: {{ .Values.cast_db.image }}
          ports:
            - containerPort: 5432
              name: cast-db
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name:  {{ .Release.Name }}
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  {{ .Release.Name }}
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name:  {{ .Release.Name }}
                  key: database
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
