---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db-sts
#  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: cast-db-{{ .Release.Name }}
    spec:
      containers:
        - name: cast-db
          image: "{{ .Values.image.cast_db }}"
          ports:
            - containerPort: 5432
              name: cast-db
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cast-db-secret
                  key: cast-db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cast-db-secret
                  key: cast-db-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: cast-db-secret
                  key: cast-db-database