# /home/cpa/Documents/CPA/44_JENKINS/DOC-REF/DR16-UTILISATION-KOMPOSE/tests/test4/cast-db-sts.yaml
## Doc off k8s/ Documentation / Concepts / Workloads / Contrôleurs / StatefulSets
### https://kubernetes.io/fr/docs/concepts/workloads/controllers/statefulset/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-casts
  template:
    metadata:
      labels:
        app: fastapi-casts
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: cast-db-secret
              key: postgres_db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cast-db-secret
              key: postgres_password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: cast-db-secret
              key: postgres_user
        image: postgres:12.1-alpine
        livenessProbe:
          exec:
            command:
            - 'pg_isready -U  -d '
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 10
        name: cast-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: postgres-data-cast
      restartPolicy: Always
      volumes:
      - name: postgres-data-cast
        persistentVolumeClaim:
          claimName: postgres-data-cast
